[package]
name = "warpgrapher_macros"
version = "0.1.1"
authors = ["Javier Vazquez"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.68", features = ["full"] }
quote = "1.0.9"
